---

- name: Initialize box
  hosts: all
  vars:
    pgp_key: 751B835F
    socat_port: 61234
  tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=300
      sudo: yes
    - name: Import PGP key
      local_action: shell gpg --export-secret-key -a '{{ pgp_key }}' | vagrant ssh -c 'gpg --import'
    - name: Trust PGP key
      local_action: shell gpg --export-ownertrust | vagrant ssh -c 'gpg --import-ownertrust'
      failed_when: false
    - name: Specify timezone
      copy: content='America/New_York\n' dest=/etc/timezone
      sudo: yes
    - name: Set timezone
      command: dpkg-reconfigure -fnoninteractive tzdata
      sudo: yes
    - name: Install socat and build packages
      apt: pkg={{ item }}
      with_items:
        - socat
        - devscripts
        - debhelper
        - quilt
      sudo: yes
    - name: Set gpg-agent socket path
      lineinfile: dest=~/.profile line="GPG_AGENT_INFO=$HOME/.gnupg/S.gpg-agent:1:1 ; export GPG_AGENT_INFO"
    - name: Run host socat
      local_action: 'shell (while true; do socat TCP-LISTEN:{{ socat_port }},bind=127.0.0.1 UNIX-CONNECT:$(echo "$GPG_AGENT_INFO" | cut -d: -f1); done) &'
    - name: Run box socat
      local_action: 'shell ssh -R{{ socat_port }}:localhost:{{ socat_port }} -l vagrant -i ~/.vagrant.d/insecure_private_key -p {{ ansible_ssh_port }} -f 127.0.0.1 "(while true; do socat UNIX-LISTEN:\$HOME/.gnupg/S.gpg-agent,unlink-close,unlink-early TCP4:localhost:{{ socat_port }}; done) &"'

# vim: set filetype=ansible :
